---
channels:
  - 'conda-forge'
  - 'defaults'
  - 'r'
  - 'dnachun'
dependencies:
  - 'python>=3.10'
  - 'pip'
  - pip:
      - 'git+file:///home/holism/workspaces/flepimop2'
  - 'yamllint'
  - 'ruff'
  - 'r-base>=4.3'
  - 'pyarrow==18.0.0'
  - 'r-arrow==18.0.0'
  - 'r-data.table>=1.17'
  - 'r-ggplot2>=3.4'
  - 'r-yaml>=2.3'
