---
channels:
  - 'conda-forge'
  - 'defaults'
  - 'r'
  - 'dnachun'
dependencies:
  - 'python>=3.10'
  - 'pip'
  - pip:
    - 'git+file:///home/holism/workspaces/flepimop2@mock-engine'
  - 'yamllint'
  - 'ruff'
  - 'r-base>=4.3'
  - 'pyarrow==18.0.0'
  - 'r-arrow==18.0.0'
