name: 'CI'

'on':
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - name: 'Install just'
        uses: 'extractions/setup-just@v3'
      - name: 'Install air'
        uses: 'posit-dev/setup-air@v1'
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'
      - name: 'Setup conda'
        uses: 'conda-incubator/setup-miniconda@v3.3.0'
        with:
          activate-environment: 'ci'
          auto-update-conda: true
          channels: 'conda-forge,defaults,r,dnachun'
      - name: 'Cache conda'
        id: 'cache-conda'
        uses: 'actions/cache@v5'
        with:
          path: '${{ env.CONDA }}/envs'
          key: "${{ runner.os }}-${{ hashFiles('environment.yaml') }}"
      - name: 'Update conda environment'
        run: 'conda env update --name ci --file environment.yaml --prune'
        if: "steps.cache-conda.outputs.cache-hit != 'true'"
      - name: 'Run ci'
        shell: bash -el {0}
        run: 'just ci'
