name: 'Integration Test'

'on':
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 9 * * 1'
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Install just'
        uses: 'extractions/setup-just@v3'
      - name: 'Install air'
        uses: 'posit-dev/setup-air@v1'
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'
      - name: 'Setup conda'
        uses: 'conda-incubator/setup-miniconda@v3'
        with:
          activate-environment: 'ci'
          auto-update-conda: true
      - name: 'Cache conda'
        id: 'cache-conda'
        uses: 'actions/cache@v4'
        with:
          path: '${{ env.CONDA }}/envs'
          key: "${{ runner.os }}-${{ hashFiles('environment.yaml') }}"
      - name: 'Update conda environment'
        run: 'conda env update --name ci --file environment.yaml --prune'
        if: "steps.cache-conda.outputs.cache-hit != 'true'"
      - name: 'Run integration test'
        shell: bash -el {0}
        run: 'just integration-test'
